# Generated by Django 3.0 on 2020-01-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hero_name', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='.')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('popularity', models.IntegerField(default=0)),
                ('ban_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('games_played', models.IntegerField(default=0)),
                ('win_total', models.IntegerField(default=0)),
                ('loss_total', models.IntegerField(default=0)),
                ('ally_1', models.CharField(default='hero_name', max_length=25)),
                ('ally_1_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ally_2', models.CharField(default='hero_name', max_length=25)),
                ('ally_2_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ally_3', models.CharField(default='hero_name', max_length=25)),
                ('ally_3_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ally_4', models.CharField(default='hero_name', max_length=25)),
                ('ally_4_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('ally_5', models.CharField(default='hero_name', max_length=25)),
                ('ally_5_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enemy_1', models.CharField(default='hero_name', max_length=25)),
                ('enemy_1_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enemy_2', models.CharField(default='hero_name', max_length=25)),
                ('enemy_2_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enemy_3', models.CharField(default='hero_name', max_length=25)),
                ('enemy_3_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enemy_4', models.CharField(default='hero_name', max_length=25)),
                ('enemy_4_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('enemy_5', models.CharField(default='hero_name', max_length=25)),
                ('enemy_5_win', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
