# Generated by Django 3.0 on 2019-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
