# Generated by Django 3.0 on 2019-12-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calc', '0004_auto_20191210_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='ally_1',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_1_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_2',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_2_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_3',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_3_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_4',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_4_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_5',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='ally_5_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_1',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_1_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_2',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_2_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_3',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_3_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_4',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_4_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_5',
            field=models.CharField(default='hero_name', max_length=25),
        ),
        migrations.AddField(
            model_name='hero',
            name='enemy_5_win',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Build',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
