# Generated by Django 3.0 on 2019-12-07 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='talent_name', max_length=75)),
                ('level', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='talent_images')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('popularity', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('win_total', models.IntegerField(default=0)),
                ('loss_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hero_name', max_length=25)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('popularity', models.IntegerField(default=0)),
                ('ban_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('games_played', models.IntegerField(default=0)),
                ('win_total', models.IntegerField(default=0)),
                ('loss_total', models.IntegerField(default=0)),
                ('talents_four', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_four_talents', to='main_calc.Talent')),
                ('talents_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_one_talents', to='main_calc.Talent')),
                ('talents_seven', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_seven_talents', to='main_calc.Talent')),
                ('talents_sixteen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_sixteen_talents', to='main_calc.Talent')),
                ('talents_ten', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_ten_talents', to='main_calc.Talent')),
                ('talents_thirteen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_thirteen_talents', to='main_calc.Talent')),
                ('talents_twenty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_twenty_talents', to='main_calc.Talent')),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('win_total', models.IntegerField(default=0)),
                ('loss_total', models.IntegerField(default=0)),
                ('win_chance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_calc.Hero')),
                ('talent_four', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_four_talent', to='main_calc.Talent')),
                ('talent_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_one_talent', to='main_calc.Talent')),
                ('talent_seven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_seven_talent', to='main_calc.Talent')),
                ('talent_sixteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_sixteen_talent', to='main_calc.Talent')),
                ('talent_ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_ten_talent', to='main_calc.Talent')),
                ('talent_thirteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_thirteen_talent', to='main_calc.Talent')),
                ('talent_twenty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_twenty_talent', to='main_calc.Talent')),
            ],
        ),
    ]
