# Generated by Django 3.0 on 2019-12-10 19:33

from django.db import migrations, models
import main_calc.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_calc', '0002_auto_20191210_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='talents_four',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='talents_one',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='talents_seven',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='talents_sixteen',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='talents_ten',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='talents_thirteen',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='talents_twenty',
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main_calc.models.get_hero_image_path),
        ),
    ]
